name: Ben
cards:
    1:
        recipient: Maureen and Dave
        gift_received: Amazon Voucher
        include_kisses: true
        output_name: "maureenanddave.pdf"

phrases:
    thankyou_for_gift:
        - Thank you very much for the %GIFT% you gave me.
        - It was so kind of you to give me a %GIFT%.
        - I was so happy to receive a %GIFT% from you this year.
        - Thanks so much for giving me a %GIFT% this year.
    generic_thankyou:
        - It made me really happy.
        - I loved it.
        - It was one of the best gifts I received.
        - It was brilliant.
        - It's so kind of you to send me gifts so often.
    goodwill:
        - Hope you're getting on really well.
        - Hope everything is good with you.
        - All the best to you.
        - I can't wait to see you again soon - it's been too long!
    future_meet_up:
        - Next time you are near by we should meet up.
        - Why don't you come over to our house next time you are in the area?
        - Next time we see you it would be great to have a meal together.

output_directory: output
page_size: A5
font: Times-Roman
font_size: 20
# Get a colour palette from the colour lovers API at http://www.colourlovers.com/api/palette/#{id}
colour_lovers_palette_id: 3612877
border_style: circles
text_padding: 30
block_spacing: 40
